print("Twinkle,twinkle,little star,")
print("              How i wonder what you are!")
print("                         Up above the world so high, ")
print("                        Like a dimand in the sky. ")
print("Twinkle,twinkle,little star,")
print("              How i wonder what you are!")